name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-branch:
          - feature-<feature_name>
          - feature-2
          - feature-3
          # Add more feature branches as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.feature-branch }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Unit Test
      run: |
      	pytest [options] [file_or_dir] [file_or_dir]

    - name: Merge feature branch with prod
      run: |
        git checkout main
        git merge ${{ matrix.feature-branch }}
        git push origin main

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ github.sha }}

    - name: Deploy to server
      run: |
        ssh user@your-server-ip 'docker pull your-docker-hub-username/your-image-name:latest'
        ssh user@your-server-ip 'docker stop your-container-name || true'
        ssh user@your-server-ip 'docker run -d -p 80:80 your-docker-hub-username/your-image-name:latest'

  rollback:
    needs: build_and_deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: stable

    - name: Rollback to previous commit
      run: |
        git reset --hard HEAD^
        git push origin dev -f

